services:
  db:
    image: postgres:15-alpine
    container_name: drizzle-muzi-local
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=muzi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis-muzi
    restart: always
    ports:
      - "6379:6379"

  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    container_name: muzi-server
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://user:password@db:5432/muzi_db
    ports:
      - "3001:3001"
    depends_on:
      - db
      - redis

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: muzi-web
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/muzi_db
      - BETTER_AUTH_SECRET=dTyG4XyZMTu65jjA8wjbeOJDB67SnOOR
      - BETTER_AUTH_URL=http://localhost:3000
      - NEXT_PUBLIC_SOCKET_URL=http://localhost:3001
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    ports:
      - "3000:3000"
    depends_on:
      - db
      - server

volumes:
  postgres_data:
